# Create network: docker network create arqui
version: "3.9"

services:
  eureka:
    hostname: eureka-server
    build: ./discovery
    networks:
     - arqui
    ports:
      - "8083:8761"
    

  gateway:
    hostname: apigateway
    build: ./apigateway
    environment:
      JWK_URI: http://keycloak:8080/realms/auth/protocol/openid-connect/certs
    networks:
      - arqui
    ports:
      - "8082:8080"


networks:
  arqui:
    driver: bridge
    external: true