eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

JWKS_URL: http://keycloak:8080/realms/auth/protocol/openid-connect/certs